import type { BookingTypeConfig } from "../interfaces/booking-type";

export const BOOKING_TYPES: Readonly<Record<string, BookingTypeConfig>> = {
  flight: {
    label: "Flight",
    dot: "bg-blue-500",
    bg: "bg-blue-50 hover:bg-blue-100",
    border: "border-l-blue-500",
    text: "text-blue-900",
    sub: "text-blue-600",
    badge: "bg-blue-100 text-blue-700",
    ring: "ring-blue-500",
    headerBg: "bg-blue-500",
  },
  ground: {
    label: "Ground School",
    dot: "bg-amber-500",
    bg: "bg-amber-50 hover:bg-amber-100",
    border: "border-l-amber-500",
    text: "text-amber-900",
    sub: "text-amber-600",
    badge: "bg-amber-100 text-amber-700",
    ring: "ring-amber-500",
    headerBg: "bg-amber-500",
  },
  simulator: {
    label: "Simulator",
    dot: "bg-violet-500",
    bg: "bg-violet-50 hover:bg-violet-100",
    border: "border-l-violet-500",
    text: "text-violet-900",
    sub: "text-violet-600",
    badge: "bg-violet-100 text-violet-700",
    ring: "ring-violet-500",
    headerBg: "bg-violet-500",
  },
  theory: {
    label: "Theory",
    dot: "bg-teal-500",
    bg: "bg-teal-50 hover:bg-teal-100",
    border: "border-l-teal-500",
    text: "text-teal-900",
    sub: "text-teal-600",
    badge: "bg-teal-100 text-teal-700",
    ring: "ring-teal-500",
    headerBg: "bg-teal-500",
  },
  exam: {
    label: "Exam",
    dot: "bg-rose-500",
    bg: "bg-rose-50 hover:bg-rose-100",
    border: "border-l-rose-500",
    text: "text-rose-900",
    sub: "text-rose-600",
    badge: "bg-rose-100 text-rose-700",
    ring: "ring-rose-500",
    headerBg: "bg-rose-500",
  },
  maintenance: {
    label: "Maintenance",
    dot: "bg-slate-500",
    bg: "bg-slate-50 hover:bg-slate-100",
    border: "border-l-slate-500",
    text: "text-slate-900",
    sub: "text-slate-600",
    badge: "bg-slate-100 text-slate-700",
    ring: "ring-slate-500",
    headerBg: "bg-slate-500",
  },
  briefing: {
    label: "Briefing",
    dot: "bg-indigo-500",
    bg: "bg-indigo-50 hover:bg-indigo-100",
    border: "border-l-indigo-500",
    text: "text-indigo-900",
    sub: "text-indigo-600",
    badge: "bg-indigo-100 text-indigo-700",
    ring: "ring-indigo-500",
    headerBg: "bg-indigo-500",
  },
} as const;
